### ISSUE TITLE
When will the code be released?

### ISSUE THREAD

**Issue by rockywind** [Len-Li/Lift3D#1]
Hello. Thank you for sharing this amazing project!

May I know when the code will be released?

I am looking forward to running this project!

**Comment by Len-Li** [comment]
Hi, 

Thanks for your interest in our project! 

I am struggling with another deadline. I will open-source the code and checkpoint in May.

**Comment by SrinjaySarkar** [comment]
Hey @Len-Li  any update on when the code might be released?

**Comment by Len-Li** [comment]
Hi, I plan to open-source the code after the NeurIPS deadline on May 25th. I need some time to clean and test the code, so the code may be open-sourced in June. I will let you know once it is finished.

**Comment by Len-Li** [comment]
> Hey @Len-Li any update on when the code might be released?

Hi, I plan to open-source the code after the NeurIPS deadline on May 25th. I need some time to clean and test the code, so the code may be open-sourced in June. I will let you know once it is finished.

**Comment by rockywind** [comment]
您好，能透露一下具体的开源计划吗？

**Comment by SrinjaySarkar** [comment]
Hi @Len-Li  any updates ?

**Comment by SrinjaySarkar** [comment]
Thanks

**Comment by Len-Li** [comment]
> Hi @Len-Li any updates ?

Hi, Srinjay, I apologize for my delay. The repo has been updated with our code and checkpoint. Please have a try. If you encounter any problems, please post them here and I will try to fix them.

**Comment by Len-Li** [comment]
> 您好，能透露一下具体的开源计划吗？

The repo has been updated with our code and checkpoint. Please have a try. Feel free to post your issue if you encounter it.

**Comment by rockywind** [comment]
您好，有计划开源相关训练代码。

**Comment by Len-Li** [comment]
> 您好，有计划开源相关训练代码。

Hi. The training code is too complex to open-source since it involves shapenet rendering and GAN inversion across different dependencies. And some of the dependencies have been lost after my internship at NIO. You can refer to similar relevant projects, such as [NeuralLift-360](https://github.com/VITA-Group/NeuralLift-360), [zero123](https://github.com/cvlab-columbia/zero123) and [nerf-from-image](https://github.com/google-research/nerf-from-image). Hope this will help.

**Comment by Len-Li** [comment]
I am closing this issue. Please feel free to re-open it if you encounter any problems.
