### ISSUE TITLE
stylegan2 generates pseudo-multiviews

### ISSUE THREAD

**Issue by xuao812500279** [Len-Li/Lift3D#7]
Hello, how do you generate pseudo-multiviews with stylegan2?

**Comment by Len-Li** [comment]
Hi,

In our implementation, we use disentangled latents to generate pseudo-multiview images. But I do not include this code in the repo because of Iossing dependency.

From my perspective, I would recommend you to use another type of 2D generator to generate pseudo-multiview images. For example, I found that recent work on diffusion model can greatly surpass stylegan, check out [zero123plus](https://github.com/SUDO-AI-3D/zero123plus) and take a look at its related work section. There are many of awesome work in this line.

Best,
Leheng Li
