### ISSUE TITLE
How to train Lift3D model with custom datasets?

### ISSUE THREAD

**Issue by hmin0503** [Len-Li/Lift3D#8]
How to train Lift3D model with custom datasets?

**Comment by Len-Li** [comment]
Hi, 

In our paper, we focus on driving datasets. If you want to experiment with other type of data, the capacity of stylegan may not suitable because it only contain car, and face checkpoint. So I would not recommend to use lift3d in other type of scenarios.

Nowadays, it would be better to leverage 2D diffusion prior rather than stylegan prior. Please check out [zero123plus](https://github.com/SUDO-AI-3D/zero123plus) and other diffusion-based method.

Best,
Leheng Li

**Comment by hmin0503** [comment]
I'd like to train a model with our own car datasets.
But i cannot find how to train the model in the README.md and your source code.
Could you give me an instruction about how to train the entire model? 

Thanks
